fix the bug of duration
PaddlePaddle/Parakeet pull request #189
Opened 2021-09-29 13:16 UTC by Jackwaterveg

2021-09-29 14:27 UTC, yt605155624 commented on tests/prepare.sh
> +    echo 'num_snapshots: 50' >> lite_train_infer.yaml
最多训练30个epoch可以，但是50个epoch才保存了模型，那不就保存不了模型吗？?

2021-09-30 02:31 UTC, zh794390558 requested changes

2021-09-30 02:31 UTC, zh794390558 commented on parakeet/models/speedyspeech.py
> +                M[0, k:k + d, j] = 1
加注释说明为什么不支持。支持后应该写成什么样子。

2021-09-30 02:31 UTC, Jackwaterveg commented on tests/prepare.sh
> +    echo 'num_snapshots: 50' >> lite_train_infer.yaml
我测试了一下，num_snapshots应该是保存模型的范围，比如当前50，那么1-50的都会保存

2021-09-30 03:35 UTC, yt605155624 approved these changes
LGTM

2021-09-30 03:36 UTC, Jackwaterveg commented on parakeet/models/speedyspeech.py
> +                M[0, k:k + d, j] = 1
已加

2021-09-30 03:38 UTC, merged